# Generated by Django 4.0 on 2022-01-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produit', models.CharField(max_length=30)),
                ('Service', models.CharField(max_length=30)),
                ('Quantitee', models.IntegerField(max_length=30)),
                ('PrixU', models.IntegerField(max_length=30)),
                ('PrixT', models.IntegerField(max_length=30)),
            ],
        ),
    ]
