# Generated by Django 4.0 on 2022-01-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_fournisseur_service_remove_stock_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Service',
            new_name='Nom',
        ),
    ]
