# Generated by Django 4.0 on 2022-01-19 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_rename_service_service_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=30)),
                ('QTEx', models.IntegerField()),
                ('QTEn', models.IntegerField()),
                ('QTS', models.IntegerField()),
                ('QTR', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.fournisseur')),
            ],
        ),
        migrations.AlterField(
            model_name='sorti',
            name='Produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stocken'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
