# Generated by Django 4.0 on 2022-01-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0005_rename_produit_sorti_designation_remove_sorti_prixt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='STOCK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=30)),
                ('QTEx', models.IntegerField()),
                ('QTEn', models.IntegerField()),
                ('QTS', models.IntegerField()),
                ('QTR', models.IntegerField()),
            ],
        ),
    ]
