# Generated by Django 4.0 on 2022-01-20 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0006_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorti',
            name='Designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='QTEn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='QTEx',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='QTR',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='QTS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocken',
            name='Designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stock'),
        ),
    ]
