# Generated by Django 4.0 on 2022-01-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0010_stockfm_sorti_utlisateur_stocken_utlisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorti',
            name='QTEx',
        ),
        migrations.RemoveField(
            model_name='sortifm',
            name='QTEx',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='QTEn',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='QTR',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='QTS',
        ),
        migrations.RemoveField(
            model_name='stocken',
            name='QTR',
        ),
        migrations.RemoveField(
            model_name='stockenfm',
            name='QTR',
        ),
        migrations.RemoveField(
            model_name='stockfm',
            name='QTEn',
        ),
        migrations.RemoveField(
            model_name='stockfm',
            name='QTR',
        ),
        migrations.RemoveField(
            model_name='stockfm',
            name='QTS',
        ),
    ]
