# Generated by Django 4.0 on 2022-01-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0017_user_stocktnkt_user_stocktfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorti',
            name='STOCKT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='STOCKT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocken',
            name='STOCKT',
            field=models.IntegerField(default=0),
        ),
    ]
