# Generated by Django 4.0 on 2022-01-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0018_sorti_stockt_stock_stockt_stocken_stockt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorti',
            name='STOCKT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='STOCKT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stocken',
            name='STOCKT',
            field=models.CharField(max_length=100),
        ),
    ]
