# Generated by Django 4.0 on 2022-01-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0021_alter_utilisateurs_stockt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='STOCKT',
            field=models.CharField(max_length=220),
        ),
        migrations.DeleteModel(
            name='STOCKT',
        ),
    ]
