# Generated by Django 4.1 on 2022-08-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0025_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='r',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h', models.CharField(max_length=200)),
            ],
        ),
    ]
