# Generated by Django 4.1 on 2022-08-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0026_r'),
    ]

    operations = [
        migrations.DeleteModel(
            name='r',
        ),
    ]
