# Generated by Django 4.1 on 2022-08-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0027_delete_r'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='Nif',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='RC',
        ),
        migrations.RemoveField(
            model_name='user',
            name='STOCKTNKT',
        ),
        migrations.RemoveField(
            model_name='user',
            name='STOCKTfl',
        ),
        migrations.RemoveField(
            model_name='utilisateurs',
            name='STOCKT',
        ),
    ]
