# Generated by Django 4.1 on 2022-08-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0028_delete_message_delete_room_remove_fournisseur_nif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Article',
            field=models.CharField(default='some thing', max_length=100),
        ),
    ]
