# Generated by Django 4.1 on 2022-08-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0029_stock_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorti',
            name='Article',
            field=models.CharField(default='some thing', max_length=100),
        ),
        migrations.AddField(
            model_name='stocken',
            name='Article',
            field=models.CharField(default='some thing', max_length=100),
        ),
    ]
