# Generated by Django 4.1 on 2022-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0030_sorti_article_stocken_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorti',
            name='Article',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Article',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stocken',
            name='Article',
            field=models.CharField(max_length=100),
        ),
    ]
