# Generated by Django 4.1 on 2022-08-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0031_alter_sorti_article_alter_stock_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorti',
            name='Article',
            field=models.CharField(default='some thing', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Article',
            field=models.CharField(default='some thing', max_length=100),
        ),
        migrations.AlterField(
            model_name='stocken',
            name='Article',
            field=models.CharField(default='some thing', max_length=100),
        ),
    ]
