# Generated by Django 4.0 on 2022-01-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Service',
        ),
        migrations.AlterField(
            model_name='stock',
            name='PrixT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='PrixU',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Quantitee',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Sorti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantitee', models.IntegerField(default=0)),
                ('PrixU', models.IntegerField(default=0)),
                ('PrixT', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('Produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stock')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.service')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='Fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Stock.fournisseur'),
            preserve_default=False,
        ),
    ]
