# Generated by Django 4.0 on 2022-01-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0004_stocken_alter_sorti_produit_delete_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sorti',
            old_name='Produit',
            new_name='Designation',
        ),
        migrations.RemoveField(
            model_name='sorti',
            name='PrixT',
        ),
        migrations.RemoveField(
            model_name='sorti',
            name='PrixU',
        ),
        migrations.RemoveField(
            model_name='sorti',
            name='Quantitee',
        ),
        migrations.RemoveField(
            model_name='stocken',
            name='QTS',
        ),
        migrations.AddField(
            model_name='sorti',
            name='QTEx',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sorti',
            name='QTR',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sorti',
            name='QTS',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
