# Generated by Django 4.0 on 2022-01-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0011_remove_sorti_qtex_remove_sortifm_qtex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorti',
            name='Utlisateur',
        ),
        migrations.RemoveField(
            model_name='stocken',
            name='Utlisateur',
        ),
    ]
