# Generated by Django 4.0 on 2022-01-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0014_alter_fournisseur_abrevation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='STOCK',
            field=models.CharField(choices=[('NKC', 'NCK'), ('ligleyte', 'ligleyte')], default=1, max_length=220),
            preserve_default=False,
        ),
    ]
