# Generated by Django 4.0 on 2022-01-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0016_remove_utilisateurs_stock_utilisateurs_stockt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='STOCKTNKT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='STOCKTfl',
            field=models.BooleanField(default=False),
        ),
    ]
