# Generated by Django 4.0 on 2022-01-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0019_alter_sorti_stockt_alter_stock_stockt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='STOCKT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockenfm',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='stockenfm',
            name='Fournisseur',
        ),
        migrations.RemoveField(
            model_name='stockenfm',
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Sortifm',
        ),
        migrations.DeleteModel(
            name='StockEnfm',
        ),
        migrations.DeleteModel(
            name='STOCKfm',
        ),
        migrations.AlterField(
            model_name='stock',
            name='STOCKT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stockt'),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='STOCKT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.stockt'),
        ),
    ]
