# Generated by Django 4.0 on 2022-01-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0022_alter_stock_stockt_delete_stockt'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='STOCKT',
            field=models.CharField(default=1, max_length=220),
            preserve_default=False,
        ),
    ]
