# Generated by Django 4.0 on 2022-01-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0023_service_stockt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='QTEn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='QTS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sorti',
            name='STOCKT',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='stocken',
            name='STOCKT',
            field=models.CharField(max_length=220),
        ),
    ]
